In [1]:
import numpy as np
import pandas as pd

In [5]:
# loading the data
df = pd.read_csv('spam.csv')
# printing head values
df.head()


Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [28]:
# df describing the dataD
df.describe()

spam
count  5572.000000
mean      0.134063
std       0.340751
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
 2   spam      5572 non-null   int64 
dtypes: int64(1), object(2)
memory usage: 87.1+ KB


In [31]:
df.columns

Index(['Category', 'Message', 'spam'], dtype='object')

In [6]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [7]:
# applyiing lamda function over the target column and converting categorial variables to quantitive
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [8]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [9]:
df.shape

(5572, 3)

In [32]:
print(df.isnull().sum())

Category    0
Message     0
spam        0
dtype: int64


In [14]:
inNull = pd.isnull(df['Category'])


In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.Message,df.spam,test_size = 0.25)

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
v =CountVectorizer()
X_train_count = v.fit_transform(X_train.values)

In [19]:
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
from sklearn.naive_bayes import MultinomialNB

In [22]:
 model = MultinomialNB()


In [23]:
model.fit(X_train_count,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [24]:
emails = ['Free Free Free, Get Maximum discount ',
         'Hello,can we meet today?']
emails_count = v.transform(emails)
model.predict(emails_count)

array([1, 0], dtype=int64)

In [25]:
X_test_count = v.transform(X_test)
model.score(X_test_count,y_test)

0.9856424982053122

In [27]:
sample_mail = ["Free DMart Voucher upto 100% discount, vouchers are fee of cost so hurry don't missout today"]
sample_mail_count = v.transform(sample_mail)
model.predict(sample_mail_count)

array([1], dtype=int64)